Add video processing, but it failed
</Users/traun.leyden/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/decorator.py:decorator-gen-176> in write_videofile(self, filename, fps, codec, bitrate, audio, audio_fps, preset, audio_nbytes, audio_codec, audio_bitrate, audio_bufsize, temp_audiofile, rewrite_audio, remove_temp, write_logfile, verbose, threads, ffmpeg_params, logger)

~/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/moviepy/decorators.py in requires_duration(f, clip, *a, **k)
     52         raise ValueError("Attribute 'duration' not set")
     53     else:
---> 54         return f(clip, *a, **k)
     55
     56

</Users/traun.leyden/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/decorator.py:decorator-gen-175> in write_videofile(self, filename, fps, codec, bitrate, audio, audio_fps, preset, audio_nbytes, audio_codec, audio_bitrate, audio_bufsize, temp_audiofile, rewrite_audio, remove_temp, write_logfile, verbose, threads, ffmpeg_params, logger)

~/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/moviepy/decorators.py in use_clip_fps_by_default(f, clip, *a, **k)
    135              for (k,v) in k.items()}
    136
--> 137     return f(clip, *new_a, **new_kw)

</Users/traun.leyden/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/decorator.py:decorator-gen-174> in write_videofile(self, filename, fps, codec, bitrate, audio, audio_fps, preset, audio_nbytes, audio_codec, audio_bitrate, audio_bufsize, temp_audiofile, rewrite_audio, remove_temp, write_logfile, verbose, threads, ffmpeg_params, logger)

~/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/moviepy/decorators.py in convert_masks_to_RGB(f, clip, *a, **k)
     20     if clip.ismask:
     21         clip = clip.to_RGB()
---> 22     return f(clip, *a, **k)
     23
     24 @decorator.decorator

~/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/moviepy/video/VideoClip.py in write_videofile(self, filename, fps, codec, bitrate, audio, audio_fps, preset, audio_nbytes, audio_codec, audio_bitrate, audio_bufsize, temp_audiofile, rewrite_audio, remove_temp, write_logfile, verbose, threads, ffmpeg_params, logger)
    324                            verbose=verbose, threads=threads,
    325                            ffmpeg_params=ffmpeg_params,
--> 326                            logger=logger)
    327
    328         if remove_temp and make_audio:

~/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_writer.py in ffmpeg_write_video(clip, filename, fps, codec, bitrate, preset, withmask, write_logfile, audiofile, verbose, threads, ffmpeg_params, logger)
    214
    215         for t,frame in clip.iter_frames(logger=logger, with_times=True,
--> 216                                         fps=fps, dtype="uint8"):
    217             if withmask:
    218                 mask = (255*clip.mask.get_frame(t))

~/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/moviepy/Clip.py in iter_frames(self, fps, with_times, logger, dtype)
    473         logger = proglog.default_bar_logger(logger)
    474         for t in logger.iter_bar(t=np.arange(0, self.duration, 1.0/fps)):
--> 475             frame = self.get_frame(t)
    476             if (dtype is not None) and (frame.dtype != dtype):
    477                 frame = frame.astype(dtype)

</Users/traun.leyden/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/decorator.py:decorator-gen-135> in get_frame(self, t)

~/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/moviepy/decorators.py in wrapper(f, *a, **kw)
     87         new_kw = {k: fun(v) if k in varnames else v
     88                  for (k,v) in kw.items()}
---> 89         return f(*new_a, **new_kw)
     90     return decorator.decorator(wrapper)
     91

~/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/moviepy/Clip.py in get_frame(self, t)
     93                 return frame
     94         else:
---> 95             return self.make_frame(t)
     96
     97     def fl(self, fun, apply_to=None, keep_duration=True):

~/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/moviepy/Clip.py in <lambda>(t)
    136
    137         #mf = copy(self.make_frame)
--> 138         newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
    139
    140         if not keep_duration:

~/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/moviepy/video/VideoClip.py in <lambda>(gf, t)
    509         if apply_to is None:
    510             apply_to = []
--> 511         return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
    512
    513     # --------------------------------------------------------------

<ipython-input-55-57f4d98078d4> in __call__(self, img)
      8     def __call__(self, img):
      9
---> 10         final_result = image_pipeline(img=img, input_image_name=None)
     11
     12         return final_result.superimposed_lane_lines_img

<ipython-input-49-ee4445fd8e7f> in image_pipeline(img, input_image_name)
     31
     32     # Calculate lane lines
---> 33     left_points, right_points, raw_lane_lines_img = fit_polynomial(binary_warped_img)
     34     final_result.left_points = left_points
     35     final_result.right_points = right_points

<ipython-input-33-1292a0a76120> in fit_polynomial(binary_warped)
      5     # Fit a second order polynomial to each using `np.polyfit`
      6     left_fit = np.polyfit(lefty, leftx, 2)
----> 7     right_fit = np.polyfit(righty, rightx, 2)
      8
      9     # Generate x and y values for plotting

~/Development/CarND-Advanced-Lane-Lines/.direnv/python-3.7.3/lib/python3.7/site-packages/numpy/lib/polynomial.py in polyfit(x, y, deg, rcond, full, w, cov)
    596         raise TypeError("expected 1D vector for x")
    597     if x.size == 0:
--> 598         raise TypeError("expected non-empty vector for x")
    599     if y.ndim < 1 or y.ndim > 2:
    600         raise TypeError("expected 1D or 2D array for y")

TypeError: expected non-empty vector for x